### ISSUE TITLE
Support more Node.js versions

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#106]
If I recall correctly, @jaydson and I have agreed that we can transpile all ES2015+ features to ES5 and drop the Node.js 0.11 and `--harmony`/`v8-argv` dependencies.

But before we start working on that, we should have a defined goal -- which engine versions will Harmonic support? I vote for:

- Stable Node.js >= 0.10;
- Latest unstable Node.js (currently 0.11.x);
- Latest io.js.

In my opinion, Node.js 0.8 is a bit too old already and is not supported by tools that we *could* make use of in the future (e.g. gulp).

So, which Node.js/io.js versions should we support?

//cc @jaydson @leobalter @felipenmoura

**Comment by jaydson** [comment]
Harmonic is a bleeding edge project.
I totally agree with you, we don't need to support old node versions.

**Comment by UltCombo** [comment]
So, what support should we aim for? Node 0.10+? I can work on a patch later tonight.

**Comment by jaydson** [comment]
Yep, Node 0.10+
