### ISSUE TITLE
Switch to rapid release publishing

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#110]
I've talked with @jaydson briefly about this, a rapid release approach has many pros:

- Users are able to consume new features and significant bug fixes soon after they're implemented;
- The feedback loop between users and developers is sped up drastically;
- Rapid releases make the project more active and "alive", having a positive effect on the community around the project by allowing users to try out new features and provide feedback much faster, thus getting the community more tightly involved with the project.

I suggest publishing a new release whenever a new feature or significant bug fix is implemented (following semantic versioning, of course).

Thoughts?

// @jaydson @leobalter

**Comment by jaydson** [comment]
Let's do it. 
Rapid releases may be the best for users and for Harmonic.

**Comment by UltCombo** [comment]
Nice! :+1:

**Comment by UltCombo** [comment]
We just have to decide how to handle the publishing workflow then.
You could keep handling it by yourself publishing new releases when you see fit, or `npm owner add ult_combo harmonic` if you want to share the responsibility. :smile:

**Comment by jaydson** [comment]
Let's keep we both as responsible for publishing Harmonic's new releases.
I've added you as owner on npm.

**Comment by UltCombo** [comment]
Thanks. `:D`
