### ISSUE TITLE
Author picture - support Gravatar

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#112]
Right now, authors have to specify a URL to their [`profilePicture`](https://github.com/es6rocks/es6rocks.github.io/commit/c4c9331fe2d874dff6550d94b4f90c4ccdfbb825#diff-9124020059a9ba2f53479ce7e28ea047R13).

Perhaps we could add a [Gravatar](https://en.gravatar.com/) option?

**Comment by UltCombo** [comment]
Of course, one could enter the gravatar hash URL directly in the profilePicture, but that's not very user friendly. Perhaps we could support the format:

```
profilePicture: gravatar/john@gmail.com
or
profilePicture: gravatar:john@gmail.com
```

Or similar.

**Comment by jaydson** [comment]
I think this kind of thing must be offered by a plugin.
But, Harmonic doesn't have (yet) the plugin mechanism :disappointed: 
Perhaps i must focus on that too.
We already have the issue #6

**Comment by UltCombo** [comment]
Gravatar would be just very few lines of code and it is quite popular, but yes, a plugin would be better suited for the task. In the future, if this is as popular as I believe, the plugin could ship with Harmonic by default.

**Comment by UltCombo** [comment]
Closing this issue for now, one can generate the hash manually until the Harmonic Gravatar plugin is made.

**Comment by jaydson** [comment]
Sure, we can ship cool plugins as much as we want.
