### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#116]
It would be nice to have a changelog, such as [npm's](https://github.com/npm/npm/blob/master/CHANGELOG.md).

**Comment by jaydson** [comment]
Sure!
And we can replicate in the releases https://github.com/es6rocks/harmonic/releases.

**Comment by UltCombo** [comment]
Oh, I didn't realize we were logging changes in the releases. IMO it is unnecessary to duplicate the changelog then, we can just use the releases log.

**Comment by jaydson** [comment]
I don't think it's totally useless.
For those who have the repo cloned can access the changelog info without going to Github.

**Comment by UltCombo** [comment]
Alright, we can work on it then. `=]`

**Comment by jaydson** [comment]
https://github.com/es6rocks/harmonic/commit/32b91a6b15530014ee3a280b7dec6c7cf136e3d0

**Comment by UltCombo** [comment]
Nice! :+1:
