### ISSUE TITLE
Tag not declared

### ISSUE THREAD

**Issue by admcode** [es6rocks/harmonic#119]
The `<main>` tag was not declared, but it is being ended on the file [tag_archives.html](https://github.com/es6rocks/harmonic/blob/fe57b82680a1757ee046f8615d6b7a1b60b948ac/src/bin/skeleton/src/templates/default/tag_archives.html)

**Comment by UltCombo** [comment]
Nice catch!

However, we should replace that whole template soon (#65), and then it should also be moved to outside of the repository (https://github.com/es6rocks/harmonic/issues/70#issuecomment-72570950).

**Comment by admcode** [comment]
OK!
See you soon!

**Comment by UltCombo** [comment]
The next release will still ship with this template, so I've fixed this. Thanks for reporting! :smile:
