### ISSUE TITLE
Update dependencies and add badge

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#121]
We have quite a few outdated dependencies at the moment:

```
C:\repos\harmonic>npm outdated --depth 0
Package     Current  Wanted  Latest  Location
less          1.7.5   1.7.5   2.4.0  less
ncp           0.5.1   0.5.1   2.0.0  ncp
stylus       0.45.1  0.45.1  0.50.0  stylus
commander     2.2.0   2.2.0   2.6.0  commander
chalk         0.5.1   0.5.1   1.0.0  chalk
permalinks    0.2.1   0.2.1   0.3.1  permalinks
should        4.6.5   4.6.5   5.0.1  should
co            3.0.6   3.0.6   4.4.0  co
```

After updating the dependencies, we can add these badges to help us keep track of the dependencies status:

[![Dependency Status](http://img.shields.io/david/es6rocks/harmonic.svg)](https://david-dm.org/es6rocks/harmonic)
[![devDependency Status](http://img.shields.io/david/dev/es6rocks/harmonic.svg)](https://david-dm.org/es6rocks/harmonic#info=devDependencies)

**Comment by jaydson** [comment]
Good.
Also, we need to check for unused deps, right?
We're still using `co`?
`less` and `stylus` may be removed when Harmonic finally support plugins.

BTW, what is the best approach updating dependencies?

**Comment by UltCombo** [comment]
> Also, we need to check for unused deps, right?

Yep.

> We're still using co?

[Yes](https://github.com/es6rocks/harmonic/blob/c91bd0cb341e92eb4adac4d1a11f0a423aca2e05/src/bin/cli/util.js#L58). I believe we can drop it after fixing #68 -- though, once we move preprocessors to plugins, there will be little point in changing the prompt module I guess.

> BTW, what is the best approach updating dependencies?

Not sure what you really mean, I guess the standard process -- bump to latest version, read docs looking for API changes and other breaking changes, update code accordingly and hope stuff doesn't break. :stuck_out_tongue_winking_eye:
