### ISSUE TITLE
New logo of Hamornic Project

### ISSUE THREAD

**Issue by italowaxman** [es6rocks/harmonic#124]
Following the concept of brother JS Rocks, the Harmonic new logo uses the same visual and typographic heritage generating uniformity. The two fused thunders give rise to "H" harmonic. Simple, direct and unique. What do you think @UltCombo @jaydson @felipenmoura @robsongajunior @leobalter and others?

![harmonic](https://cloud.githubusercontent.com/assets/2953435/6771529/5a75959c-d0bf-11e4-88d9-247b8576b1da.jpg)
![captura de tela 2015-03-22 as 18 17 42](https://cloud.githubusercontent.com/assets/2953435/6771534/8953e238-d0bf-11e4-8d28-eeabe23c933e.png)
![captura de tela 2015-03-22 as 18 18 11](https://cloud.githubusercontent.com/assets/2953435/6771536/8df6dc82-d0bf-11e4-9df9-4171d6412c36.png)

**Comment by UltCombo** [comment]
holy..! AWESOME! :star2:
Thanks for the magnificent work @italowaxman, congratz. :smile: 

Side note: got to remember to file an issue in the [Babel website repo](https://github.com/babel/babel.github.io) to change our logo once we merge this in.

**Comment by jaydson** [comment]
:clap: :clap: :clap: :clap: 
Awesome job @italowaxman

**Comment by italowaxman** [comment]
Awesome! We approve now or need some more feedback?

**Comment by jaydson** [comment]
More than approved.
Can you link here the images so i can update our Github home page?

BTW, i'm thinking about creating an Harmonic's Twitter profile.
Maybe @harmonic_ssg or something like that.

**Comment by italowaxman** [comment]
Could you provide me the image size of Github home page?

**Comment by robsongajunior** [comment]
Great Job x)

**Comment by joridos** [comment]
WOWOW awesome, great work.

**Comment by jaydson** [comment]
Hey @italowaxman , something that fits well here: https://github.com/es6rocks/harmonic

**Comment by UltCombo** [comment]
Or we could change the layout a bit, and use the logo replacing the heading text. Thoughts @jaydson ?

**Comment by jaydson** [comment]
Yep, we can use the logo as a cool header now :)

**Comment by UltCombo** [comment]
Perhaps we could use the SVG logo directly in the readme and the site?
This way, modern browsers will have excellent rendering independent of resizing/zoom levels (specially useful for mobile devices) and changing the image size is easily done through CSS or HTML attributes.

**Comment by jaydson** [comment]
:+1:

**Comment by italowaxman** [comment]
Today convert the logo to SVG and create the image to github. The SVG file i attached here?

**Comment by UltCombo** [comment]
@italowaxman yes, I think this one would be a perfect logo/header:
![](http://i.imgur.com/Txayy07.png)

It'd be great if you could provide the SVG version. :smiley:

**Comment by italowaxman** [comment]
Here thw Harmonic Black SVG logo:
https://drive.google.com/file/d/0B_aLtMalJUl7b1dWUlpsaE9XMU0/view?usp=sharing

And here the yellow bolt version of SVG logo:
https://drive.google.com/file/d/0B_aLtMalJUl7U1ZLeDNPMThFN28/view?usp=sharing

**Comment by UltCombo** [comment]
@italowaxman Nice, though the font-face for "The next static site generator" is different. Did you change it intentionally? Or did you export the SVG from a computer that doesn't have the original font installed? Or was it a problem with the export?

**Comment by UltCombo** [comment]
@italowaxman Oh wait, it is my computer that doesn't have the `NexaLight` installed. Perhaps you could vectorize the text? Or add a similar fallback font. Right now, Chrome is falling back to Times New Roman, which is a serif font and that doesn't look good with the overall logo design imo.

**Comment by UltCombo** [comment]
By vectorize I mean, most graphic editors have an option to transform text into curves/vectors. That would be great for portability, so that the logo would render the same everywhere independent of having the font installed.

**Comment by italowaxman** [comment]
I Just confused the version of the logo and converting that typography was not converted into curves. Follow the correct links, including the nexa light source. Sorry for the confusion ;)

Black:
https://drive.google.com/file/d/0B_aLtMalJUl7cU9wLVVTdU1LQkk/view?usp=sharing
Yellow:
https://drive.google.com/file/d/0B_aLtMalJUl7ekFGZ3hBaTNZcGM/view?usp=sharing
Nexa Light:
https://drive.google.com/open?id=0B_aLtMalJUl7cndscllucHhnYlU&authuser=0

**Comment by UltCombo** [comment]
@italowaxman Nice work! Perfect.
@jaydson which version should we use in the readme and the site?
The all-black one seems fine to me.
The yellow thunder looks okay to me too, but I'm not sure if it wouldn't feel a bit out of place being the only "bright" part.

**Comment by jaydson** [comment]
The all-black :metal:

**Comment by UltCombo** [comment]
:metal:

BTW, what do we do with the old logo? Do we just replace it with the new one or rename/move and also keep the old one in the repository?
I guess there's little use to keeping the old logo around, but yeah.

**Comment by jaydson** [comment]
I think we can keep the old logo in the repo :)

**Comment by UltCombo** [comment]
See #127

**Comment by UltCombo** [comment]
@italowaxman Looks like we forgot about the licensing details. Since you're contributing to Harmonic which is MIT-licensed, I assume your work (logo) is also MIT-licensed, right?
This may not matter much to us, but it is important to know when others want to display our branding.

**Comment by italowaxman** [comment]
@UltCombo when you talk about MIT license and use of the logo by others, would refer to any applicable rule or prohibition on the use of the same? The logo was built in a simple way so that your application is basically done by anyone, anywhere and has visibility in most cases. How about creating a repository on correct application of the logo?

**Comment by UltCombo** [comment]
> How about creating a repository on correct application of the logo?

@italowaxman Makes sense. Perfects adding a text file to the repository or a page to the Harmonic website would be better. I've sketched up some branding usage here: https://github.com/babel/babel.github.io/issues/201

Perhaps we can add a page to the Harmonic website similar to https://github.com/logos
cc @jaydson

**Comment by italowaxman** [comment]
@UltCombo https://github.com/babel/babel.github.io/issues/201 it's basically it even had thought. Regarding the idea of doing a page like the Github logos, it's very cool, can pass an air even more professional and confiable. @jaydson what do you think?

**Comment by UltCombo** [comment]
Nice work, perhaps a bit more of contrast would be nice.

**Comment by jaydson** [comment]
>Perhaps we can add a page to the Harmonic website similar to https://github.com/logos
:+1: 

>Github logos, it's very cool, can pass an air even more professional and confiable.
:+1:

**Comment by phenriqueleao** [comment]
Awesome @italowaxman !!!

**Comment by italowaxman** [comment]
Thx @phenriqueleao ;)

**Comment by felipenmoura** [comment]
bah! achei que ficou de mais, esse logo!
\,,/

**Comment by jaydson** [comment]
English please @felipenmoura
