### ISSUE TITLE
Update keywords

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic#125]
> Put keywords in it. It's an array of strings. This helps people discover your package as it's listed in npm search.

**Comment by jaydson** [comment]
Metalsmith uses:
```javascript
"keywords": [
"static",
"file",
"site",
"website",
"blog",
"generator",
"markdown",
"jekyll",
"wintersmith",
"blacksmith"
]
```

**Comment by jaydson** [comment]
Docpad uses:
```javascript
"keywords": [
"document management system",
"dms",
"content management system",
"cms",
"static site generator",
"generator",
"static file server",
"server",
"web",
"web framework",
"framework",
"web development",
"development",
"dev",
"build and deployment",
"builder",
"build",
"compiler",
"compile",
"parser",
"parse",
"renderer",
"render",
"templating",
"templates",
"language agnostic",
"website",
"blog",
"cli",
"tool",
"utility",
"scaffold"
],
```

**Comment by UltCombo** [comment]
Oh damn, I didn't realize we didn't have keywords in the `package.json`.
I guess we can use a good part of those keywords above. `=]`

**Comment by jaydson** [comment]
I think a good set of keywords would be:

```javascript
"keywords": [
    "ssg",
    "generator",
    "blog",
    "scaffold",
    "markdown",
    "website",
    "static",
    "static generator",
    "static site generator",
    "ES6",
    "ES7",
  ]
```

**Comment by UltCombo** [comment]
Perhaps add ES2015/ES2016 as well? I'd also add `jekyll`, seeing as people often search for alternatives using another tool's name.

**Comment by jaydson** [comment]
I'll add ES2015/ES2016.
About `jekyll`, i don't know. This seems to be like "stealing the game"? Don't you think?
I just don't know if it is a like Google search, you know. When doing something like this is considered bad.
Not technically bad, but seen as bad by the community.

**Comment by UltCombo** [comment]
I see your point.
I was just thinking about searchability, e.g. people who may use "jekyll" to search for static site generators because they may not know a more generic term.
But yeah, we can live without that keyword, so it is probably better this way. :+1:

**Comment by UltCombo** [comment]
Issue solved then.

**Comment by UltCombo** [comment]
Oh, you committed to the `keywords` branch instead of master, let's wait for the merge to close this then.

**Comment by jaydson** [comment]
@UltCombo now we have to update on npm, right?

**Comment by jaydson** [comment]
Done.

**Comment by UltCombo** [comment]
:+1:
