### ISSUE TITLE
`harmonic config` success message

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#136]
Right now, `harmonic config` has the same success message as `harmonic init`:

> Your Harmonic website skeleton was successfully created!
> Now, browse the project dir and have fun.

This doesn't make much sense as the skeleton is already in place when the user runs `harmonic config`.

**Comment by UltCombo** [comment]
fixed by e20d315fdefc156abcf0fb879136302600d7c0e3

**Comment by jaydson** [comment]
Good one.
