### ISSUE TITLE
Where to place auxiliary files for posts

### ISSUE THREAD

**Issue by soapdog** [es6rocks/harmonic#138]
Where should I place auxiliary files for posts such as images and downloadable content? Since the public folder is overwritten every time I run the build/run command I am not sure where to place such content.

Shouldn't we have a merge folder that on build would be copied to public much like theme developers do? Without this, harmonic users will need to change the theme node module to carry their files...

Should I do a PR?

**Comment by jaydson** [comment]
That's makes sense.
You mean files not related to the theme, right?

I think we lost this feature when we split themes outside harmonic's core.
Do you have a working branch with such feature?

//cc @UltCombo

**Comment by UltCombo** [comment]
@jaydson We could add a `src/resources` directory which gets copied over to `public/resources` on build. Perhaps we could even do it in the existing [`copyResources` method](https://github.com/es6rocks/harmonic/blob/52d0e4d8ad43446b8542a295354850b390a3c127/src/bin/parser.js#L263-L272)

What do you think?

**Comment by jaydson** [comment]
Yep, should work.
But perhaps, we should copy `src/resources/*` to `public/*`.
I mean, copy just the content inside `resources`.

**Comment by UltCombo** [comment]
@jaydson sounds good. `:D`

**Comment by UltCombo** [comment]
And we should copy it after building everything and copying the theme files, so that any of the generated/theme files can be overwritten with a custom user resource.

**Comment by UltCombo** [comment]
Then it may make sense to split the copying in two methods: `copyThemeResources` and `copyCustomResources` (or `copyUserResources`)

**Comment by jaydson** [comment]
Good approach :)

**Comment by soapdog** [comment]
Yep, that sounds good to me. :+1:

**Comment by jaydson** [comment]
@soapdog 
>Do you have a working branch with such feature?

**Comment by soapdog** [comment]
Not yet but I can do it today and send a new PR if you guys want....

**Comment by UltCombo** [comment]
Fixed by #141, available since v0.3.0
