### ISSUE TITLE
gh-pages branch

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#50]
Looks like Harmonic's current gh-pages branch (live at http://es6rocks.com/harmonic/) does not have much use. Maybe delete the branch, or start it over using Harmonic itself to generate the pages?

**Comment by jaydson** [comment]
I think with this new issue #101 we can move forward and delete that branch, right?

**Comment by UltCombo** [comment]
I believe so. `=]`

**Comment by jaydson** [comment]
`gh-pages` branch removed.

**Comment by UltCombo** [comment]
:+1:
