### ISSUE TITLE
Using ES6 modules

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic#76]
Node's CommonJS implementation is awesome.
But, one of Harmonic goals is push ES6 forward, using its new features when possible, testing, etc.
We can try to use ES6 modules on Harmonic with:
https://github.com/esnext/es6-module-transpiler
https://github.com/ModuleLoader/es6-module-loader

cc:// @UltCombo

**Comment by UltCombo** [comment]
6to5 v3+ did a very nice job with its CJS interop implementation. I no longer oppose importing native CJS with ESM syntax.

@jaydson feel free to write `import fs from 'fs';` and such if you'd still like to. :smiley:

**Comment by jaydson** [comment]
Wow, that's awesome!

**Comment by UltCombo** [comment]
I'll update the code to use ESM syntax then and close this issue.

**Comment by jaydson** [comment]
Awesome work @UltCombo !

**Comment by UltCombo** [comment]
:smile:
