### ISSUE TITLE
Replace GLOBALs with a dedicated store

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#80]
This shall aid testing as well.

**Comment by UltCombo** [comment]
bfe1adacd8257270f0c39d5e4c2f7f99add35979 and https://github.com/es6rocks/harmonic/commit/beb9caff64a1dc4e2bffa0d10184af3d482e73b9 removed all the global variables by either storing their values as properties of the Parser class instance (now called Harmonic class) or returning these values from the functions which generate them and passing them forward as arguments.

**Comment by UltCombo** [comment]
![](http://gifsec.com/wp-content/uploads/GIF/2014/03/Party-Time-Party-Hard-GIF.gif)

**Comment by jaydson** [comment]
![](http://i.giphy.com/L2UdIWuCRbUL6.gif)
