### ISSUE TITLE
child_process: customFds option is deprecated, use stdio instead

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic#91]
Every time i run `harmonic` i get this message.

**Comment by UltCombo** [comment]
This is an issue with v8-argv, here's the [source](https://github.com/logicalparadox/v8-argv/blob/ad05c00a0b2fff46d6d9d0420ddfe508e3e5348f/index.js#L48).

Reported issue: logicalparadox/v8-argv#3

**Comment by jaydson** [comment]
Great.
I saw your PR, let's wait for the approval on v8-argv project?
I mean, now we're transpiling the code. Is v8-argv yet necessary?
Questions questions :p

**Comment by UltCombo** [comment]
We're using Node's native generators, that's why we need v8-argv to add the `--harmony` flag.

**Comment by jaydson** [comment]
Yes, but we're using native generators because i started this way.
My point here is we're transpiling everything, and generators can be transpiled too, and we don't need to force the "user" to have 0.11.* node env.

PS1: I don't think is bad thing to have node 0.11.* as requirement
PS2: For sure native generators are better than transpiled

**Comment by UltCombo** [comment]
Thing is, even if we transpile generators, we won't be able to use co and co-dependent libraries unless they were transpiled too.

Right now, Harmonic depends on co-prompt, so transpiling only the Harmonic code wouldn't work in older Node versions as co-prompt uses native generators.

**Comment by jaydson** [comment]
Hey, this issue was solved by one of your commits.
It was on purpose or an accident?
Anyway, good job :+1:

**Comment by UltCombo** [comment]
On purpose, yes -- #106 removed the v8-argv dependency which was causing the issue.
I forgot to write it in the PR, then I reminded about it when I was away from the computer and ended up forgetting again hah.
Thanks for confirming that it is fixed. :+1:

**Comment by jaydson** [comment]
great!
