### ISSUE TITLE
[dev] Grunt and npm link

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic#93]
Every time i build Harmonic with `grunt`, the global `harmonic` disappear from the path, so i must to run `npm link`.

**Comment by UltCombo** [comment]
@jaydson please try the [npm-link branch](https://github.com/es6rocks/harmonic/tree/npm-link) and see if it fixes this issue. `=]`

**Comment by jaydson** [comment]
Working perfectly :+1:
